### ISSUE TITLE
Message for Jerry

### ISSUE THREAD

**Issue by steepleian** [steepleian/weewx-Weather34-development#1]
Hi Jerry,
Your e-mail is constantly blocking me. As last resort sending my suggestion via Github

Just working my way slowly through all the changes and updating the settings page.

Should the services selection string have enclosing double quotes?

Also one thing has just occurred to me. Is it possible to include comments in weewx.conf when w34_installer.py is executed? I will include the information in the install instructions but it is useful imo to have a prompt in the file as well.

I am thinking along these lines: -

[Weather34WebServices]
 
    # air quality, your own latitude, longitude, token and interval in seconds are required
    # Example https://api.waqi.info/feed/geo:51.940;-0.987/?token=yourtokenhere
    aq_url = https://api.waqi.info/feed/geo:lat;lon/?token=
    aq_interval = 900
    aq_filename = /var/www/html/weewx/w34weather/jsondata/aqi.txt

    # Dark Sky, your own latitude, longitude, API key, language, units and interval in seconds required
    # Example https://api.forecast.io/forecast/yourtokenhere/51.94,-0.987?lang=en&units=uk2
    ds_url = https://api.forecast.io/forecast/api_key/lat,lon?lang=xx&units=xx
    ds_interval = 3600
    ds_filename = /var/www/html/weewx/w34weather/jsondata/darksky.txt

    # Weather Underground, your own latitude, longitude, API key, language, units and interval in seconds required
    # Example https://api.weather.com/v3/wx/forecast/daily/5day?geocode=51.94,-0.987&language=en&format=json&units=h&apiKey=yourapikeyhere
    wu_url = https://api.weather.com/v3/wx/forecast/daily/5day?geocode=lat,lon&language=xx&format=json&units=h&apiKey=
    wu_interval = 300
    wu_filename = /var/www/html/weewx/w34weather/jsondata/wuforecast.txt

    # Earthquake reports interval in seconds required
    eq_url = https://earthquake-report.com/feeds/recent-eq?json
    eq_interval = 300
    eq_filename = /var/www/html/weewx/w34weather/jsondata/eqnotification.txt

    # K-Index reports interval in seconds required
    ki_url = https://services.swpc.noaa.gov/products/geospace/planetary-k-index-dst.json
    ki_interval = 43200
    ki_filename = /var/www/html/weewx/w34weather/jsondata/kindex.txt

    # Metar reports airport code, API Key and interval in seconds required
    # Example https://api.checkwx.com/metar/EGTK/decoded
    # Example X-API-Key:yourapikeyhere
    me_url = https://api.checkwx.com/metar/xxxx/decoded
    me_header = X-API-Key:api_key
    me_interval = 300
    me_filename = /var/www/html/weewx/w34weather/jsondata/metar34.txt

    # Purpleair reports device ID and interval in seconds required
    # Example https://www.purpleair.com/json?show=38365
    pu_url = https://www.purpleair.com/json?show=
    pu_interval = 3600
    pu_filename = /var/www/html/weewx/w34weather/jsondata/purpleair.txt

    # Meteoalrm European weather warnings country code, region code and interval in seconds required
    # Example http://192.168.1.232/weewx/weather34/eualert.php?country=UK&region=013
    al_url = http://xxx.xxx.xxx.xxx:yy/weewx/w34weather/eualert.php?country=xx&region=xxx
    al_interval = 3600
    al_filename = /var/www/html/weewx/w34weather/jsondata/meteoalarm.txt

    # Select the services you require by creating a string of the services above
    # Example services = "ds.me.eq.ki.wu.aq.al.ah.ao.aa.pu"
    services = ""

[Weather34CloudCover]
    # Insert your own continent, latitude and longitude in the two URLs below
    # Example https://api.sat24.com/crop?type=visual5hdcomplete&lat=51.94&lon=-0.987&width=300&height=300&zoom=1.00&continent=eu
    enable = True
    db_field = signal8
    cc_interval = 300
    cc1_url = https://api.sat24.com/crop?type=visual5hdcomplete&lat=xx&lon=xx&width=300&height=300&zoom=1.00&continent=xx
    cc1_filename = /tmp/sat1.png
    cc2_url = https://api.sat24.com/crop?type=infraPolair&lat=xx&lon=xx&width=300&height=300&zoom=1.00&continent=xx
    cc2_filename = /tmp/sat2.png

Many thanks,
Ian

**Comment by balloonhotair** [comment]
Hi,
Strange nobody else is having an issue, but I will check into it.
Does not have to be enclosed with double quotes since all are strings, so it can even be blank ie services =
Yes you can include comments since it is ConfigObj, just use #

**Comment by balloonhotair** [comment]
Comments did not work adding them now

**Comment by steepleian** [comment]
Yep, I just tried as well but getting syntax error.

**Comment by balloonhotair** [comment]
Hi Ian,
This will work.
    '#aq_url':'This is a URL', 
    '#aq_interval':'This is a interval', 
    '#aq_filename':'This is a filename', 
will produce output this in weewx.conf
    #aq_url = This is a URL
    #aq_interval = This is a interval
    #aq_filename = This is a filename

Not sure on doing the newline

**Comment by balloonhotair** [comment]
This will give you close to a blankline
'#aq':'',

**Comment by balloonhotair** [comment]
Hi Ian,
So here is an example doing air quality.
    '#aq1':'air quality, your own latitude, longitude, token and interval in seconds are required',
    '#aq2':'Example https://api.waqi.info/feed/geo:51.940;-0.987/?token=yourtokenhere',
    'aq_url':'https://api.waqi.info/feed/geo:lat;lon/?token=',
    'aq_interval':'900',
    'aq_filename':'/var/www/html/weewx/w34weather/jsondata/aqi.txt',
    '#aq':'end',

[Weather34WebServices]
    #aq1 = air quality, your own latitude, longitude, token and interval in seconds are required
    #aq2 = Example https://api.waqi.info/feed/geo:51.940;-0.987/?token=yourtokenhere
    aq_url = https://api.waqi.info/feed/geo:lat;lon/?token=
    aq_interval = 900
    aq_filename = /var/www/html/weewx/w34weather/jsondata/aqi.txt
    #aq = end

**Comment by balloonhotair** [comment]
Another choice is to put all the comments before the Weather34WebServices section. Let me know if you like this better.

**Comment by balloonhotair** [comment]
Hi Ian,
Here is a better choice and it looks like you cannot send the some of the urls in an email. That is what getting blocked.

"config_entries3":'''=
'Weather34WebServices' :
"# air quality, your own latitude, longitude, token and interval in seconds are required\n"
"# Example https://api.waqi.info/feed/geo:51.940;-0.987/?token=yourtokenhere\n"

"# Dark Sky, your own latitude, longitude, API key, language, units and interval in seconds required\n"
"# Example https://api.forecast.io/forecast/yourtokenhere/51.94,-0.987?lang=en&units=uk2\n"

"# Weather Underground, your own latitude, longitude, API key, language, units and interval in seconds required\n"
"# Example https://api.weather.com/v3/wx/forecast/daily/5day?geocode=51.94,-0.987&language=en&format=json&units=h&apiKey=yourapikeyhere\n"

"# Earthquake reports interval in seconds required\n"

"# K-Index reports interval in seconds required\n"

"# Metar reports airport code, API Key and interval in seconds required\n"
"# Example https://api.checkwx.com/metar/EGTK/decoded\n"
"# Example X-API-Key:yourapikeyhere\n"

"# Purpleair reports device ID and interval in seconds required\n"
"# Example https://www.purpleair.com/json?show=38365\n"

"# Meteoalrm European weather warnings country code, region code and interval in seconds required\n"
"# Example http://192.168.1.232/weewx/weather34/eualert.php?country=UK&region=013\n"

"# Select the services you require by creating a string of the services above\n"
"# Example services = ds.me.eq.ki.wu.aq.al.ah.ao.aa.pu\n"
{
    'aq_url':'https://api.waqi.info/feed/geo:lat;lon/?token=',
    'aq_interval':'900',
    'aq_filename':'/var/www/html/weewx/w34weather/jsondata/aqi.txt',
    'ds_url':'https://api.forecast.io/forecast/api_key/lat,lon?lang=xx&units=xx',
    'ds_interval':'3600',
    'ds_filename':'/var/www/html/weewx/w34weather/jsondata/darksky.txt',
    'wu_url':'https://api.weather.com/v3/wx/forecast/daily/5day?geocode=lat,lon&language=xx&format=json&units=h&apiKey=',
    'wu_interval':'300',
    'wu_filename':'/var/www/html/weewx/w34weather/jsondata/wuforecast.txt',
    'eq_url':'https://earthquake-report.com/feeds/recent-eq?json',
    'eq_interval':'300',
    'eq_filename':'/var/www/html/weewx/w34weather/jsondata/eqnotification.txt',
    'ki_url':'https://services.swpc.noaa.gov/products/geospace/planetary-k-index-dst.json',
    'ki_interval':'43200',
    'ki_filename':'/var/www/html/weewx/w34weather/jsondata/kindex.txt',
    'me_url':'https://api.checkwx.com/metar/xxxx/decoded',
    'me_header':'X-API-Key:api_key',
    'me_interval':'300',
    'me_filename':'/var/www/html/weewx/w34weather/jsondata/metar34.txt',
    'pu_url':'https://www.purpleair.com/json?show=',
    'pu_interval':'3600',
    'pu_filename':'/var/www/html/weewx/w34weather/jsondata/purpleair.txt',
    'al_url':'http://xxx.xxx.xxx.xxx:yy/weewx/w34weather/eualert.php?country=xx&region=xxx',
    'al_interval':'3600',
    'al_filename':'/var/www/html/weewx/w34weather/jsondata/meteoalarm.txt',
    'services':''           
        }''',

Here is what I get in the output.

#
################################################################################

# air quality, your own latitude, longitude, token and interval in seconds are required
# Example https://api.waqi.info/feed/geo:51.940;-0.987/?token=yourtokenhere
# Dark Sky, your own latitude, longitude, API key, language, units and interval in seconds required
# Example https://api.forecast.io/forecast/yourtokenhere/51.94,-0.987?lang=en&units=uk2
# Weather Underground, your own latitude, longitude, API key, language, units and interval in seconds required
# Example https://api.weather.com/v3/wx/forecast/daily/5day?geocode=51.94,-0.987&language=en&format=json&units=h&apiKey=yourapikeyhere
# Earthquake reports interval in seconds required
# K-Index reports interval in seconds required
# Metar reports airport code, API Key and interval in seconds required
# Example https://api.checkwx.com/metar/EGTK/decoded
# Example X-API-Key:yourapikeyhere
# Purpleair reports device ID and interval in seconds required
# Example https://www.purpleair.com/json?show=38365
# Meteoalrm European weather warnings country code, region code and interval in seconds required
# Example http://192.168.1.232/weewx/weather34/eualert.php?country=UK&region=013
# Select the services you require by creating a string of the services above
# Example services = ds.me.eq.ki.wu.aq.al.ah.ao.aa.pu

[Weather34WebServices]
    aq_url = https://api.waqi.info/feed/geo:lat;lon/?token=
    aq_interval = 900
    aq_filename = /var/www/html/weewx/w34weather/jsondata/aqi.txt
    ds_url = https://api.forecast.io/forecast/api_key/lat,lon?lang=xx&units=xx
    ds_interval = 3600
    ds_filename = /var/www/html/weewx/w34weather/jsondata/darksky.txt
    wu_url = https://api.weather.com/v3/wx/forecast/daily/5day?geocode=lat,lon&language=xx&format=json&units=h&apiKey=
    wu_interval = 300
    wu_filename = /var/www/html/weewx/w34weather/jsondata/wuforecast.txt
    eq_url = https://earthquake-report.com/feeds/recent-eq?json
    eq_interval = 300
    eq_filename = /var/www/html/weewx/w34weather/jsondata/eqnotification.txt
    ki_url = https://services.swpc.noaa.gov/products/geospace/planetary-k-index-dst.json
    ki_interval = 43200
    ki_filename = /var/www/html/weewx/w34weather/jsondata/kindex.txt
    me_url = https://api.checkwx.com/metar/xxxx/decoded
    me_header = X-API-Key:api_key
    me_interval = 300
    me_filename = /var/www/html/weewx/w34weather/jsondata/metar34.txt
    pu_url = https://www.purpleair.com/json?show=
    pu_interval = 3600
    pu_filename = /var/www/html/weewx/w34weather/jsondata/purpleair.txt
    al_url = http://xxx.xxx.xxx.xxx:yy/weewx/w34weather/eualert.php?country=xx&region=xxx
    al_interval = 3600
    al_filename = /var/www/html/weewx/w34weather/jsondata/meteoalarm.txt
    services =


I will submit this change.

**Comment by steepleian** [comment]
Hi Jerry,

I got that working like that last night and I am working through them now
so will add to development repo when finished.
I have yet to get the web services working however and another user who has
tried the development repo reports the same. When I have finished the
updating I will look at it more closely and send you the logs.

Cheers,
Ian

**Comment by balloonhotair** [comment]
Hi Ian,
I have updated the install and the three config files with the comments you listed above in the section for web services

**Comment by steepleian** [comment]
I've just done the same:-) I did not see any changes that you had made.

**Comment by steepleian** [comment]
Yours look better than mine I will roll back to yours. I also had added
Aeris Weather alerts and forecasts, I will add those to yours.

As I had had the repo page open for over 30min, as I had not refreshed I
did not see your updates.

**Comment by steepleian** [comment]
Got an error with the packaged installer on the test rig

 sudo python3 w34_installer.py
!!! THIS INSTALL IS USING PYTHON VERSION 3.7.3 IS THIS CORRECT? (Yes/No)yes
Install will continue with Python Version 3.7.3
1 -> macos.conf
2 -> setup_py.conf
3 -> packaged.conf
Enter the NUMBER of the installer config file 3
Installer Config file packaged.conf was chosen.
Traceback (most recent call last):
  File "w34_installer.py", line 106, in <module>
    distutils.file_util.copy_file(weewx_config_file, weewx_config_file +
"." + str(int(time.time())))
  File "/usr/lib/python3.7/distutils/file_util.py", line 105, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy 'weewx.conf': doesn't exist
or not a regular file
can't copy 'weewx.conf': doesn't exist or not a regular file

**Comment by steepleian** [comment]
OK back in sync now, correct files in place. Install worked with
packaged.py but no comments appeared. Wiped the comments I had inserted and
left the bare bones.

[Weather34WebServices]
    aq_url = https://api.waqi.info/feed/geo:lat;lon/?token=
    aq_interval = 900
    aq_filename = /var/www/html/weewx/w34weather/jsondata/aqi.txt
    ds_url =
https://api.forecast.io/forecast/api_key/lat,lon?lang=xx&units=xx
    ds_interval = 3600
    ds_filename = /var/www/html/weewx/w34weather/jsondata/darksky.txt
    wu_url =
https://api.weather.com/v3/wx/forecast/daily/5day?geocode=lat,lon&language=xx&format=json&units=h&apiKey=
    wu_interval = 300
    wu_filename = /var/www/html/weewx/w34weather/jsondata/wuforecast.txt
    eq_url = https://earthquake-report.com/feeds/recent-eq?json
    eq_interval = 300
    eq_filename = /var/www/html/weewx/w34weather/jsondata/eqnotification.txt
    ki_url =
https://services.swpc.noaa.gov/products/geospace/planetary-k-index-dst.json
    ki_interval = 43200
    ki_filename = /var/www/html/weewx/w34weather/jsondata/kindex.txt
    me_url = https://api.checkwx.com/metar/xxxx/decoded
    me_header = X-API-Key:api_key
    me_interval = 300
    me_filename = /var/www/html/weewx/w34weather/jsondata/metar34.txt
    pu_url = https://www.purpleair.com/json?show=
    pu_interval = 3600
    pu_filename = /var/www/html/weewx/w34weather/jsondata/purpleair.txt
    al_url = http://xxx.xxx.xxx.xxx:yy
/weewx/w34weather/eualert.php?country=xx&region=xxx
    al_interval = 3600
    al_filename = /var/www/html/weewx/w34weather/jsondata/meteoalarm.txt
    services =
#
################################################################################

[Weather34CloudCover]
    enable = True
    db_field = signal8
    cc_interval = 300
    cc1_url =
https://api.sat24.com/crop?type=visual5hdcomplete&lat=xx&lon=xx&width=300&height=300&zoom=1.00&continent=xx
    cc1_filename = /tmp/sat1.png
    cc2_url =
https://api.sat24.com/crop?type=infraPolair&lat=xx&lon=xx&width=300&height=300&zoom=1.00&continent=xx
    cc2_filename = /tmp/sat2.png

**Comment by balloonhotair** [comment]
Ok, if the section exists nothing is written. If you delete the section then it will write the new info. Also the overwrite option should do it. I will test to see if overwrite is working with config entries

**Comment by balloonhotair** [comment]
The installer now allows over write of config entries

**Comment by steepleian** [comment]
All working OK now. Have added a comment to Weather34CloudCover stanza of the install config files as well.
