### ISSUE TITLE
Barometer Display Issue

### ISSUE THREAD

**Issue by EmeraldMu** [steepleian/weewx-Weather34-development#146]
Issue: There is no reading on the barometer (except for a constant mark at -45 degrees)

My weather station is roughly 850m above sea level. The air pressure is "usually" around 940Mb, which is below the minimum shown on the barometer for the skin.
The pressure can be seen correctly in the almanac.
This is the last line of the w34realtime.txt file:
`30/03/23 23:25:28 16.7 56 7.8 0.9 1.1 266 0.0 0.0 939.9 W 1 m/s C mb mm 36.7 0.9 1.3 1.3 0.0 NULL NULL 16.7 -0.6 21.8 15:20 10.1 08:15 1.5 16:10 1.6 00:05 943.3 12:05 938.9 20:40 4.10.2 0 1.6 15.9 17.0 NULL NULL NULL 263 0.0 0 0 0 N 1103 m 15.4 12.6 0.0 NULL NULL NULL NULL NULL 1.6`

**Comment by steepleian** [comment]
That pressure is very low. Most WeeWX skins I have seen that include gauges have a minimum of 970hPa. I am assuming that your device does not adjust for sea level. What driver extension do you use?https://claydonsweather.org.uk/weewx/divumwx On 30 Mar 2023, at 22:29, EmeraldMu ***@***.***> wrote:﻿
Issue: There is no reading on the barometer (except for a constant mark at -45 degrees)
My weather station is roughly 850m above sea level. The air pressure is "usually" around 940Mb, which is below the minimum shown on the barometer for the skin.
The pressure can be seen correctly in the almanac.
This is the last line of the w34realtime.txt file:
30/03/23 23:25:28 16.7 56 7.8 0.9 1.1 266 0.0 0.0 939.9 W 1 m/s C mb mm 36.7 0.9 1.3 1.3 0.0 NULL NULL 16.7 -0.6 21.8 15:20 10.1 08:15 1.5 16:10 1.6 00:05 943.3 12:05 938.9 20:40 4.10.2 0 1.6 15.9 17.0 NULL NULL NULL 263 0.0 0 0 0 N 1103 m 15.4 12.6 0.0 NULL NULL NULL NULL NULL 1.6

**Comment by EmeraldMu** [comment]
Good afternoon,
No, the device makes no adjustment. It's basically using the WS1 driver, adapted for the DFRobot message string (https://wiki.dfrobot.com/APRS_Weather_Station_Sensor_Kit_SEN0186)
The pressure is roughly 8kPa lower here than at sea level; should I just put the adjustment in the driver?

**Comment by steepleian** [comment]
Yes that is what I would do. I am not familiar with the hardware that you are using but I know for instance my hardware adjusts for sea level.https://claydonsweather.org.uk/weewx/divumwx On 31 Mar 2023, at 14:46, EmeraldMu ***@***.***> wrote:﻿
Good afternoon,
No, the device makes no adjustment. It's basically using the WS1 driver, adapted for the DFRobot message string (https://wiki.dfrobot.com/APRS_Weather_Station_Sensor_Kit_SEN0186)
The pressure is roughly 8kPa lower here than at sea level; should I just put the adjustment in the driver?

**Comment by EmeraldMu** [comment]
Thanks. I wasn't happy with hard coding the value, so I've altered the driver so it now has a function to calculate the pressure variance at altitude. 
I'm still not getting a barometer reading though.

`31/03/23 16:57:27 20.0 56 10.9 0.0 0.5 251 0.0 0.0 1022.7 WSW 1 m/s C mb mm 42.3 83.2 1.3 1.3 0.0 NULL NULL 20.0 -1.7 21.8 14:20 12.8 04:30 1.7 13:20 3.2 04:10 1022.8 16:55 938.5 05:15 4.10.2 0 0.0 19.5 21.7 NULL NULL NULL NULL 0.0 0 1 0 N 1132 m 19.9 9.0 581.0 NULL NULL NULL NULL NULL 0.0`


![image](https://user-images.githubusercontent.com/58751577/229156107-dbeb65e0-d413-47b2-b870-4591c1602d44.png)

**Comment by steepleian** [comment]
There is a value there in the real-time 1022.7https://claydonsweather.org.uk/weewx/divumwx On 31 Mar 2023, at 15:58, EmeraldMu ***@***.***> wrote:﻿
Thanks. I wasn't happy with hard coding the value, so I've altered the driver so it now has a function to calculate the pressure variance at altitude.
I'm still not getting a barometer reading though.
31/03/23 16:57:27 20.0 56 10.9 0.0 0.5 251 0.0 0.0 1022.7 WSW 1 m/s C mb mm 42.3 83.2 1.3 1.3 0.0 NULL NULL 20.0 -1.7 21.8 14:20 12.8 04:30 1.7 13:20 3.2 04:10 1022.8 16:55 938.5 05:15 4.10.2 0 0.0 19.5 21.7 NULL NULL NULL NULL 0.0 0 1 0 N 1132 m 19.9 9.0 581.0 NULL NULL NULL NULL NULL 0.0

**Comment by EmeraldMu** [comment]
Yeah, I can see the pressure reading in the data, but the gauge itself is steadfast refusing to budge!
As a side note, the almanac has updated as would be expected.

**Comment by EmeraldMu** [comment]
Scrap this. I pulled the version direct from the repo instead of from v4.3
All resolved.
