### ISSUE TITLE
Not updating database

### ISSUE THREAD

**Issue by k6bpm** [steepleian/weewx-Weather34-development#76]
Station: Davis Vantage PRO 2 with Weather Envoy attached to WeeWX/Weather34 running on dedicated RPi 4.

I had a power outage 2 days ago and the Weather envoy lost power for 3 hours. The RPi did not lose power as it has a battery backup. 

Since the power was restored, no historical data is being recorded. Any graph I select ends on the date and time of the power outage. Current data is being received and w34realtime.txt is being updated correctly. 

I didn't notice this until last night when it was windy and I noticed no gusts or high wind speeds were being updated. The only things displayed are actual real time data.

**Comment by balloonhotair** [comment]
This not a skin issue but most probably a corrupt data logger. Please search the weewx forum there is a ton of postings dealing with this exact issue.

**Comment by k6bpm** [comment]
That was it. Thanks for pointing me in the right direction. All working fine now.
