### ISSUE TITLE
CSS Items

### ISSUE THREAD

**Issue by k6bpm** [steepleian/weewx-Weather34-development#78]
I would like to change the background color of the top caption bar and the bottom status bar on the main page tiles.  I haven't been able to identify the correct CSS item and was wondering if someone could tell me what CSS values to change?

**Comment by steepleian** [comment]
Brian,
I don’t have easy access to my files at the moment so this is from memory. For the top, have a look at the classes in menu.php and for the bottom, have a look at the footer section in index.php. This will give you an idea of classes to search for in the main dark and light CSS files in the CSS folder.
Ian

**Comment by k6bpm** [comment]
The page header and footer are fine. The colors I am trying to locate are the headers and footers for the individual tiles (I call them tiles) like Temperature, Rainfall Today, etc. On a smartphone when the tiles are stacked the backgrounds are only slightly lighter than the page background and it makes it harder for an occasional visitor to make the distinction. It looks like it is continuous text and not organized into groups of data.

**Comment by steepleian** [comment]
Ok, so in class weather-item you need to set border-bottom and border-shadow to the colours you require.

**Comment by k6bpm** [comment]
Perfect! Thanks Ian!
